### ISSUE TITLE
detail panel

### ISSUE THREAD

**Issue by elizabethsjudd** [Explorys/ink#51]
Main Contacts on Portal

**Comment by elizabethsjudd** [comment]
The design needs updated to be more inline with Studio's expanding panel.

**Comment by TashaMC** [comment]
See contacts page design.  
Path:
[EngineeringInternal/ux/projects/portal/playbacks/onboardingportalR4.pptx](https://ibm.box.com/s/qdc03fc4y8qe7powb89gftd8ekw1jb3q)

**Comment by elizabethsjudd** [comment]
PR Submitted
