### ISSUE TITLE
Refreshing Collapsable Table duplicates EventListeners

### ISSUE THREAD

**Issue by Craigimus1990** [Explorys/ink#88]
In onboarding-portal; the alerts table allows pagination and table resizing. I am calling Ink_CollapsableTables.refresh() whenever one of these actions occurs in order to add collapsable elements to the new elements in the table. 

When the table is resized to a larger size (i.e. 10 elements on a page -> 25 elements on a page), the new elements correctly get an event listener, but the original 10 elements get a *second* event listener. This causes them to become non-collapsable (since one listener sets the row to "open", then the second listener removes it). These rows remain uncollapsable until another resize or pagination occurs.

**Comment by elizabethsjudd** [comment]
As per discussions with Seeders we are going to add a setting to allow applications to disable my event handlers so that Angular can do all of the even binding.  Would you prefer this approach?
